---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: homelab
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      readarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/readarr
              tag: 0.4.15.2787
            env:
              READARR__APP__INSTANCENAME: readarr
              READARR__APPLICATION_URL: 'https://radarr.porgy-monitor.ts.net'
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: Forms
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__LOG__DBENABLED: "False"
              READARR__LOG__LEVEL: info
              READARR__SERVER__PORT: &port 8787
              READARR__UPDATE__BRANCH: develop
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 750Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - *app
    persistence:

      config:
        existingClaim: readarr-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.0.147"
            path: /mnt/md0/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
