---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: homelab
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      prowlarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.6.1.5509@sha256:ce5d6bdd5be6529f503df77aa9d2bad20239031d7c660406e8fb1c6d621dd020
            env:
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__APP__THEME: dark
              PROWLARR__AUTH__METHOD: External
              PROWLARR__AUTH__REQUIRED: DisabledForLocalAddresses
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
              PROWLARR__SERVER__PORT: &port 80
              PROWLARR__UPDATE__BRANCH: develop
              DOTNET_SYSTEM_NET_DISABLEIPV6: "1"
              TZ: America/New_York
            # envFrom: &envFrom
              # - secretRef:
              #     name: prowlarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          gluetun:
            env:
              VPN_SERVICE_PROVIDER: "private internet access"
              OPENVPN_USER: p2669071
              OPENVPN_PROTOCOL: tcp
              SERVER_REGIONS: "US Chicago"
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16,192.168.0.0/16,1.1.1.1/32
              DNS_ADDRESS: 1.1.1.1
            envFrom:
              - secretRef:
                  name: sabnzbd-vpn-secret
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.41.3
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              privileged: true
              allowPrivilegeEscalation: true
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - *app
    persistence:
      config:
        existingClaim: prowlarr-config
      tmp:
        type: emptyDir
