---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
  namespace: homelab
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      plex:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.42.2.10156@sha256:9ad8a3506e1d8ebda873a668603c1a2c10e6887969564561be669efd65ae8871
            env:
              PLEX_NO_AUTH_NETWORKS: 192.168.0.0/24
              PLEX_ADVERTISE_URL: 192.168.0.55:32400
              TZ: America/New_York
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /identity
            #         port: &port 32400
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                gpu.intel.com/i915: 1
                memory: 10Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 10000]
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        existingClaim: plex-config
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server
      plex-cache:
        existingClaim: plex-cache
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Logs
      media:
        type: nfs
        server: 192.168.0.147
        path: /mnt/md0/media
        globalMounts:
          - path: /media
            readOnly: false
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
    service:
      app:
        controller: *app
        type: LoadBalancer
        ports:
          http:
            port: &port 32400
            nodePort: *port
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
              - *app
