apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-configmap
  namespace: homelab
data:
  openclaw.json: |
    {
      "gateway": {
        "bind": "0.0.0.0:18789",
        "mode": "local",
        "auth": {
          "mode": "token"
        }
      },
      "controlUi": {
        "enabled": true
      },
      "agents": {
        "defaults": {
          "model": {
            "primary": "opencode-go/kimi-k2.6"
          }
        }
      },
      "channels": {
        "discord": {
          "enabled": true,
          "token": {
            "source": "env",
            "provider": "default",
            "id": "DISCORD_BOT_TOKEN"
          },
          "dmPolicy": "pairing",
          "guilds": {
            "134033291471749120": {
              "requireMention": false,
              "users": ["134033064593588224"]
            }
          }
        }
      }
    }
