apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: node-feature-discovery
spec:
  interval: 1m
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: Revision
      version: "0.16.4"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
      interval: 1m
  values:
