apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: pihole-password # Name of the Kubernetes secret to create
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pihole-password
        property: password
