---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ./searxng.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - ./resources/limiter.toml
      - ./resources/settings.yml
generatorOptions:
  disableNameSuffixHash: true
