---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
  namespace: homelab
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      searxng:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2025.11.21-e245cade2@sha256:acf424bf6799d85336eb93da0bd205e7e53d8221d7a45dba0a378ad5b45ff3b9
            env:
              SEARXNG_BASE_URL: https://search.porgy-monitor.ts.net
              SEARXNG_URL: https://search.porgy-monitor.ts.net
              SEARXNG_PORT: &port 8080
              SEARXNG_REDIS_URL: redis://searxng-redis.homelab.svc.cluster.local:6379/0
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE

      redis:
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
        strategy: RollingUpdate
        containers:
          redis:
            image:
              repository: docker.io/valkey/valkey
              tag: 9.0.3
            args:
              - --save
              - ""
              - --appendonly
              - "no"
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      app:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/funnel: "true"
        defaultBackend:
          service:
            name: searxng-app
            port:
              number: *port
        tls:
          - hosts:
              - search

    persistence:
      config:
        enabled: true
        type: configMap
        name: searxng-configmap
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
          - path: /etc/searxng/limiter.toml
            subPath: limiter.toml
            readOnly: true
      tmpfs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /var/cache/searxng
          - path: /tmp
