apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-test
  namespace: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: operator-oauth # Name of the Kubernetes secret to create
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: tailscale-client-secret
        property: password
    - secretKey: client_id
      remoteRef:
        key: tailscale-client-id
        property: password
