---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: homelab
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  values:
    controller:
      strategy: Recreate
    controllers:
      sonarr:
        containers:
          app:
            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__APP__THEME: dark
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__DBENABLED: false
              SONARR__LOG__LEVEL: debug
              SONARR__SERVER__PORT: &port 80
              SONARR__UPDATE__BRANCH: develop
              TZ: America/New_York
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.16.2946
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 2000Mi
              requests:
                cpu: 10m
                memory: 250Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
        supplementalGroups:
          - 10000
    service:
      app:
        controller: sonarr
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - *app
    persistence:
      config:
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.0.147
        path: /mnt/md0/media
        globalMounts:
          - path: /media
      downloads:
        type: nfs
        server: 192.168.0.147
        path: /mnt/md0/media/downloads
        globalMounts:
          - path: /downloads
            subPath: usenet
