---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: loop
        ensure: present
        comment: "User for loop"
        login: true
        superuser: false
        passwordSecret:
          name: loop-db-credentials
