---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
spec:
  instances: 3
  storage:
    size: 20Gi
    storageClass: longhorn
  managed:
    roles:
      - name: vaultwarden
        login: true
        ensure: present
        comment: "User for vaultwarden"
        superuser: false
        inRoles:
          - pg_database_owner
        passwordSecret:
          name: vaultwarden-db-credentials
