---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
spec:
  instances: 3
  storage:
    size: 20Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: vaultwarden
        ensure: present
        comment: "User for vaultwarden"
        login: true
        superuser: false
        passwordSecret:
          name: vaultwarden-db-credentials
      - name: speedtest
        ensure: present
        comment: "User for speedtest"
        login: true
        superuser: false
        passwordSecret:
          name: speedtest-db-credentials

