apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: loop
  namespace: database
spec:
  cluster:
    name: postgresql
  ensure: present
  name: loop
  owner: loop
  allowConnections: true
