apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: homelab
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday
              - type: rss
                limit: 10
                collapse-after: 3
                cache: 12h
                feeds:
                  - url: https://selfh.st/rss/
                    title: selfh.st
                    limit: 4
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed
          - size: full
            widgets:
              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters
              - type: videos
                channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw   # Linus Tech Tips
                  - UC7s6t5KCNwRkb7U_3-E1Tpw   # Jake Baldino
                  - UCR-DXc1voovS8nhAvccRZhg   # Jeff Geerling
                  - UCo71RUe6DX4w-Vd47rFLXPg   # Typecraft
                  - UCOk-gHyjcWZNj3Br4oxwh0A   # Techno Tim
                  - UCsnGwSIHyoYN0kiINAGUKxg   # Wolfgang's Channel
              - type: group
                widgets:
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                  - type: reddit
                    subreddit: pittsburgh
                    show-thumbnails: true
                  - type: reddit
                    subreddit: homelab
                    show-thumbnails: true
                  - type: reddit
                    subreddit: worldnews
                    show-thumbnails: true
          - size: small
            widgets:
              - type: weather
                location: Arlington, Virginia, United States
                units: imperial
                hour-format: 12h
              - type: markets
                markets:
                  - symbol: ^IXIC
                    name: NASDAQ
                  - symbol: ^GSPC
                    name: S&P 500
                  - symbol: FSLY
                    name: Fastly
      - name: Homelab
        columns:
          - size: small
            widgets:
            - type: server-stats
              servers:
                - type: local
                  name: Homelab
            - type: repository
              repository: JonSchaeffer/k3s-homelab
              pull-requests-limit: 5
              commits-limit: 3
          - size: full
            widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: AudioBookShelf
                  url: http://audiobookshelf
                  icon: si:audiobookshelf
                - title: Overseerr
                  url: http://overseerr:5055
                  icon: si:overseerr
                - title: Plex
                  url: http://plex:32400
                  icon: si:plex
                - title: Prowlarr
                  url: http://prowlarr
                  icon: si:proton
                - title: qBittorrent
                  url: http://qbittorrent
                  icon: si:qbittorrent
                - title: Radarr
                  url: http://radarr
                  icon: si:radarr
                - title: Radarr-UHD
                  url: http://radarr-uhd
                  icon: si:radarr
                - title: Readarr
                  url: http://readarr
                  icon: si:readarr:8787
                - title: Sabnzbd
                  url: http://Sabnzbd:8080
                  icon: si:sabnzbd
                - title: Sonarr
                  url: http://sonarr
                  icon: si:sonarr
                - title: Tautulli
                  url: http://tautulli:8181
                  icon: si:tautulli
                - title: Speedtest
                  url: http://speedtest
                  icon: si:speedtest

