---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app onepassword-connect
  namespace: kube-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  values:
    controllers:
      onepassword-connect:
        strategy: RollingUpdate
        containers:
          api:
            image:
              repository: docker.io/1password/connect-api
              tag: 1.8.1
            env:
              XDG_DATA_HOME: &dataDir /config
              OP_HTTP_PORT: &port 8080
              OP_BUS_PORT: 11220
              OP_BUS_PEERS: localhost:11221
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 15
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
            resources: &resources
              requests:
                cpu: 10m
              limits:
                memory: 256M
          sync:
            image:
              repository: docker.io/1password/connect-sync
              tag: 1.8.1
            env:
              XDG_DATA_HOME: *dataDir
              OP_HTTP_PORT: &syncPort 8081
              OP_BUS_PORT: 11221
              OP_BUS_PEERS: localhost:11220
              OP_SESSION:
                valueFrom:
                  secretKeyRef:
                    name: onepassword-secret
                    key: 1password-credentials.json
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /heartbeat
                    port: *syncPort
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *syncPort
                  initialDelaySeconds: 15
            securityContext: *securityContext
            resources: *resources
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: onepassword-connect
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
              - *app
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: *dataDir
