# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: homelab
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        type: statefulset
        containers:
          freshrss:
            image:
              repository: freshrss/freshrss
              tag: 1.26.2
              pullPolicy: IfNotPresent
            env:
              TZ: America/New_York
              CRON_MIN: "18,48"
              DOMAIN: "https://rss.porgy-monitor.ts.net/"
      fivefilters-full-text-rss:
        containers:
          fivefilters-full-text-rss:
            image:
              repository: heussd/fivefilters-full-text-rss
              tag: latest@sha256:6deb1a6e2378a7772e07555f437674458c26e31273776d2f432961e3eae5cd3d
              pullPolicy: IfNotPresent
            securityContext:
              runAsUser: 33  # www-data user ID
              runAsGroup: 33 # www-data group ID
              fsGroup: 33    # Ensures mounted volumes have correct group ownership
    service:
      freshrss:
        controller: *app
        ports:
          http:
            port: &port 80
      fivefilters-full-text-rss:
        controller: fivefilters-full-text-rss
        ports:
          http:
            port: *port
    ingress:
      freshrss:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - rss
      fivefilters-full-text-rss:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: freshrss-fivefilters-full-text-rss
            port:
              number: *port
        tls:
          - hosts:
            - fivefilters
    persistence:
      config:
        existingClaim: freshrss-config
        advancedMounts:
          freshrss:
            freshrss:
              - path: /var/www/FreshRSS/data
      cache:
        existingClaim: freshrss-config-ftr
        advancedMounts:
          fivefilters-full-text-rss:
            fivefilters-full-text-rss:
              - path: /var/www/html/cache/rss
