# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: homelab
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      freshrss:
        type: statefulset
        containers:
          freshrss:
            image:
              repository: freshrss/freshrss
              tag: 1.26.3
              pullPolicy: IfNotPresent
            env:
              TZ: America/New_York
              CRON_MIN: "18,48"
              DOMAIN: "https://rss.porgy-monitor.ts.net/"
      fivefilters-full-text-rss:
        pod:
          securityContext:
            runAsUser: 33      # www-data
            runAsGroup: 33     # www-data
            fsGroup: 33        # Makes mounted volumes accessible to www-data
        containers:
          fivefilters-full-text-rss:
            image:
              repository: heussd/fivefilters-full-text-rss
              tag: latest@sha256:71deac43da094ac84d92eaabc0d82bc6764c43f23e45085f7bee32ca3ded01de
              pullPolicy: IfNotPresent
    service:
      freshrss:
        controller: *app
        ports:
          http:
            port: &port 80
      fivefilters-full-text-rss:
        controller: fivefilters-full-text-rss
        ports:
          http:
            port: *port
    ingress:
      freshrss:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - rss
      fivefilters-full-text-rss:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/funnel: "true"
        defaultBackend:
          service:
            name: freshrss-fivefilters-full-text-rss
            port:
              number: *port
        tls:
          - hosts:
            - fivefilters
    persistence:
      config:
        existingClaim: freshrss-config
        advancedMounts:
          freshrss:
            freshrss:
              - path: /var/www/FreshRSS/data
      cache:
        existingClaim: freshrss-config-ftr
        advancedMounts:
          fivefilters-full-text-rss:
            fivefilters-full-text-rss:
              - path: /var/www/html/cache
