apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
