apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stirling-pdf
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://stirling-tools.github.io/Stirling-PDF-chart
