---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
  namespace: homelab
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      scrypted:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          app:
            image:
              repository: ghcr.io/koush/scrypted
              tag: v0.144.1-noble-full
            env:
              SCRYPTED_SECURE_PORT: &secure 11443
            resources:
              requests:
                cpu: 125m
                memory: 1Gi
              limits:
                memory: 3Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: *app
        type: LoadBalancer
        ports:
          http:
            port: &port 11080
          https:
            port: *secure
          rebroadcast:
            port: 34135
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
              - *app
    persistence:
      config:
        enabled: true
        existingClaim: scrypted-config
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      recordings:
        type: nfs
        server: 192.168.0.147
        path: /mnt/md0/media
        advancedMounts:
          scrypted:
            app:
              - path: /recordings
                subPath: scrypted
