---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./audiobookshelf
  - ./bazarr
  - ./degoog
  - ./dispatcharr
  - ./esphome
  - ./homeassistant
  - ./immich
  - ./kometa
  - ./maintainerr
  - ./ntfy
  - ./openclaw
  - ./overseer
  - ./paperless-ngx
  - ./pihole
  - ./pinchflat
  - ./plex
  - ./prowlarr
  - ./qbittorrent
  - ./radarr
  - ./radarr-uhd
  - ./sabnzbd
  - ./scrypted
  - ./sonarr
  - ./stirling-pdf
  - ./tautulli
