---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-uhd-config
  namespace: homelab
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-uhd-cache
  namespace: homelab
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
