apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf
  namespace: homelab
spec:
  defaultBackend:
    service:
      name: stirling-pdf-stirling-pdf-chart
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - pdf
