apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: homelab
spec:
  defaultBackend:
    service:
      name: pihole-web
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - pihole
---
apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: homelab
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale # Use Tailscale as the Load Balancer
  ports:
    - name: pihole-dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: pihole-dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: pihole
