apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: prometheus-prometheus
      port:
        number: 9090
  ingressClassName: tailscale
  tls:
    - hosts:
        - prometheus
