apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: Revision
      version: "0.23.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 1m
  values:
