apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage
      reconcileStrategy: Revision
      version: "2.0.2"
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
      interval: 1m
  values:
    config:
      services:
        - Services:
            - Pihole:
                href: https://pihole.porgy-monitor.ts.net/admin
                widget:
                  type: pihole
                  url: http://pihole-web
                  key: 998ed4d621742d0c2d85ed84173db569afa194d4597686cae947324aa58ab4bb
                    # version: 5 # required if running v6 or higher, defaults to 5
            - Speedtest Tracker:
                href: https://speedtest.porgy-monitor.ts.net
                widget:
                  type: speedtest
                  url: http://speedtest-tracker
            - Grafana:
                href: https://grafana.porgy-monitor.ts.net
            - Stirling PDF:
                href: https://pdf.porgy-monitor.ts.net
            - Vaultwarden:
                href: https://vaultwarden.porgy-monitor.ts.net

      bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/JonSchaeffer
          - ArtifactHub:
              - abbr: AH
                href: https://artifacthub.io
          - Tailscale:
              - abbr: TS
                href: https://login.tailscale.com/admin/machines
          - 
      widgets:
      - resources:
          # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
          backend: kubernetes
          expanded: true
          cpu: true
          memory: true
      - search:
          provider: duckduckgo
          focus: true
          showSearchSuggestions: true
          target: _blank
      - datetime:
          text_size: xl
          format:
            timeStyle: short
            dateStyle: short
            hour12: true


    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true
