apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-device-plugin
  namespace: inteldeviceplugins-system
spec:
  interval: 1m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      reconcileStrategy: Revision
      version: "0.32.0"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 1m
  values:
