apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      chart: pihole
      reconcileStrategy: Revision
      version: "2.27.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 1m
  values:
    persistentVolumeClaim:
      enabled: true
    serviceDns:
      mixedService: false
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
