apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 1m
  releaseName: redis
  chartRef:
    kind: OCIRepository
    name: redis
    namespace: flux-system
  values:
