apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf
      reconcileStrategy: Revision
      version: "v1.5.0"
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
      interval: 1m
  values:
