apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: Revision
      version: "v0.31.2"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
  values:
    database:
      type: postgresql
      existingSecret: "vaultwarden-db-creds"
      existingSecretKey: "uri"
