apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: Revision
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  values:
    defaultBackupStore:
      backupTarget: "s3://k3s-homelab-longhorn-backup@us/"
      backupTargetCredentialSecret: "longhorn-gcp-backup-creds"
      pollInterval: "180"
