---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: homelab
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      sabnzbd:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.1@sha256:0bd045af783ba13da0a9bf029ae5e574c9dcfcc65f1cd348ffc06b2660be90ff
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.homelab
                sabnzbd.homelab.svc,
                sabnzbd.homelab.svc.cluster,
                sabnzbd.homelab.svc.cluster.local,
                sabnzbd.porgy-monitor.ts.net,
            resources:
              requests:
                cpu: 247m
                memory: 161M
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          securityContext:
            fsGroup: 568
            runAsGroup: 568
            runAsUser: 568
            fsGroupChangePolicy: "OnRootMismatch"
          # gluetun:
            # env:
            #   VPN_SERVICE_PROVIDER: "private internet access"
            #   OPENVPN_USER: p2669071
            #   SERVER_REGIONS: "US Virginia"
            #   PORT_FORWARD_ONLY: false
            #   DNS_ADDRESS: 1.1.1.1
            # envFrom:
            #   - secretRef:
            #       name: sabnzbd-vpn-secret
            # image:
            #   repository: ghcr.io/qdm12/gluetun
            #   tag: v3.40.0
            # securityContext:
            #   capabilities:
            #     add:
            #       - NET_ADMIN
            #   privileged: true
            #   allowPrivilegeEscalation: true
            #   runAsUser: 0 # Run as root to ensure proper permissions
            #   runAsGroup: 0
            #   runAsNonRoot: false

    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - *app
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.0.147"
            path: /mnt/md0/media/downloads
        globalMounts:
          - path: /downloads
            subPath: usenet
      incomplete:
        enabled: true
        type: emptyDir
