apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-vpn-secret
  namespace: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: sabnzbd-vpn-secret # Name of the Kubernetes secret to create
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: sabnzdb-password
        property: password
