---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reader-backend
  namespace: reader
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  values:
    controller:
      strategy: Recreate
    controllers:
      reader-backend:
        containers:
          app:
            env:
              DB_HOST: postgres
              DB_PORT: 5432
              DB_NAME: postgres
              DB_USER: postgres
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: password
              FIVEFILTERS_URL: http://fivefilters:80
            image:
              repository: ghcr.io/jonschaeffer/go-reader-backend
              tag: sha-c7a4037
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 10m
                memory: 250Mi
    service:
      app:
        controller: *app
        ports:
          reader-backend:
            port: &port 8080
    ingress:
      app:
        enabled: true
        className: tailscale
        defaultBackend:
          service:
            name: *app
            port:
              number: *port
        tls:
          - hosts:
            - *app
