---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app fivefilters
  namespace: reader
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  values:
    controller:
      strategy: Recreate
    controllers:
      fivefilters:
        containers:
          app:
            env:
              APACHE_RUN_USER: "www-data"
              APACHE_RUN_GROUP: "www-data"
            image:
              repository: heussd/fivefilters-full-text-rss
              tag: latest
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 10m
                memory: 250Mi
    service:
      app:
        controller: *app
        ports:
          postgres:
            port: &port 80
