---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app postgres
  namespace: reader
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  values:
    controller:
      strategy: Recreate
    controllers:
      postgres:
        containers:
          app:
            env:
              POSTGRES_USER: postgres
              POSTGRES_DB: postgres
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: postgres-secret
                    key: password
              PGDATA: /var/lib/postgresql/data/pgdata
            image:
              repository: postgres
              tag: 18.0-alpine
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 1000Mi
              requests:
                cpu: 10m
                memory: 250Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 999
    service:
      app:
        controller: *app
        ports:
          postgres:
            port: &port 5432
    persistence:
      data:
        existingClaim: postgres-data
        globalMounts:
          - path: /var/lib/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: reader
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
